Synth.cpp: IVoice Class Reference
IVoice Class Reference abstract
#include <synth.h>
Public Member Functions
virtual ~IVoice ()
virtual void quiet (void)=0
virtual void step (void)=0
virtual void setfreq (float f)=0
virtual void keydown (void)=0
virtual void keyup (void)=0
virtual int32_t output (void)=0
virtual bool idle (void)=0
virtual void ioctl (uint32_t, uint32_t)=0
Detailed Description
Definition at line 45 of file synth.h.
Constructor & Destructor Documentation
virtual IVoice::~IVoice () inline virtual
Definition at line 47 of file synth.h.
Member Function Documentation
virtual bool IVoice::idle (void) pure virtual
Implemented in NoisyVoice, TwoSquaresVoice, and SimpleVoice.
Referenced by Synth::keydown().
virtual void IVoice::ioctl (uint32_t , uint32_t) pure virtual
Implemented in NoisyVoice, TwoSquaresVoice, and SimpleVoice.
Referenced by Synth::ioctl().
virtual void IVoice::keydown (void) pure virtual
Implemented in NoisyVoice, TwoSquaresVoice, and SimpleVoice.
Referenced by Synth::keydown().
virtual void IVoice::keyup (void) pure virtual
Implemented in NoisyVoice, TwoSquaresVoice, and SimpleVoice.
Referenced by Synth::keyup().
virtual int32_t IVoice::output (void) pure virtual
Implemented in NoisyVoice, TwoSquaresVoice, and SimpleVoice.
Referenced by Synth::get_12_bit_value().
virtual void IVoice::quiet (void) pure virtual
Implemented in NoisyVoice, TwoSquaresVoice, and SimpleVoice.
virtual void IVoice::setfreq (float f) pure virtual
Implemented in NoisyVoice, TwoSquaresVoice, and SimpleVoice.
Referenced by Synth::keydown().
virtual void IVoice::step (void) pure virtual
Implemented in NoisyVoice, TwoSquaresVoice, and SimpleVoice.
Referenced by Synth::compute_sample().
The documentation for this class was generated from the following file:
teensy/synth.h