Synth.cpp: ISynth Class Reference
ISynth Class Reference abstract
#include <synth.h>
Public Member Functions
virtual ~ISynth ()
virtual void quiet (void)=0
virtual void add (IVoice *voice)=0
virtual void keydown (int8_t pitch)=0
virtual void keyup (int8_t pitch)=0
virtual uint8_t get_sample (uint32_t *x)=0
virtual void write_sample (void)=0
virtual void compute_sample (void)=0
virtual void ioctl (uint32_t, uint32_t)=0
Detailed Description
Definition at line 58 of file synth.h.
Constructor & Destructor Documentation
virtual ISynth::~ISynth () inline virtual
Definition at line 60 of file synth.h.
Member Function Documentation
virtual void ISynth::add (IVoice * voice) pure virtual
Implemented in Synth.
virtual void ISynth::compute_sample (void) pure virtual
Implemented in Synth.
Referenced by loop().
virtual uint8_t ISynth::get_sample (uint32_t * x) pure virtual
Implemented in Synth.
virtual void ISynth::ioctl (uint32_t , uint32_t) pure virtual
Implemented in Synth.
Referenced by play_tune().
virtual void ISynth::keydown (int8_t pitch) pure virtual
Implemented in Synth.
Referenced by Key::keydown(), and play_tune().
virtual void ISynth::keyup (int8_t pitch) pure virtual
Implemented in Synth.
Referenced by Key::keyup(), and play_tune().
virtual void ISynth::quiet (void) pure virtual
Implemented in Synth.
virtual void ISynth::write_sample (void) pure virtual
Implemented in Synth, ThreadSafeSynth, and ThreadSafeSynth.
The documentation for this class was generated from the following file:
teensy/synth.h