Synth.cpp: test Namespace Reference
test Namespace Reference
Functions
def f
Variables
tuple CMD = ("g++ -Wall -g -D__ARM=0 -Iteensy -o foo test.cpp teensy/synth.cpp teensy/tune.cpp teensy/tests.cpp")
just_tests = False
string fname = "quux.aiff"
string player = "afplay"
S = foo.samples
tuple q = aifc.open(fname, "wb")
Function Documentation
def test.f (x)
Definition at line 35 of file test.py.
Referenced by Synth.keydown(), Filter.setF(), and NoisyVoice.setfreq().
Variable Documentation
string test.CMD = ("g++ -Wall -g -D__ARM=0 -Iteensy -o foo test.cpp teensy/synth.cpp teensy/tune.cpp teensy/tests.cpp")
Definition at line 6 of file test.py.
string test.fname = "quux.aiff"
Definition at line 27 of file test.py.
test.just_tests = False
Definition at line 9 of file test.py.
string test.player = "afplay"
Definition at line 30 of file test.py.
tuple test.q = aifc.open(fname, "wb")
Definition at line 48 of file test.py.
Referenced by Filter.setQ().
test.S = foo.samples
Definition at line 41 of file test.py.