Synth.cpp: teensy/tests.cpp File Reference
tests.cpp File Reference
#include <stdio.h>
#include "tests.h"
Functions
static int8_t test1 (void)
static int8_t test2 (void)
static int8_t test3 (void)
int8_t run_tests (void)
Function Documentation
int8_t run_tests (void)
Definition at line 24 of file tests.cpp.
Referenced by FunctionKey::keydown(), and main().
static int8_t test1 (void) static
Definition at line 4 of file tests.cpp.
Referenced by run_tests().
static int8_t test2 (void) static
Definition at line 14 of file tests.cpp.
Referenced by run_tests().
static int8_t test3 (void) static
Definition at line 19 of file tests.cpp.
Referenced by run_tests().